### ISSUE TITLE
Error writing data to auth/ssh/config: Error making API request.

### ISSUE THREAD

**Issue by sh0shin** [42wim/vault-plugin-auth-ssh#1]
Used the latest git checkout
```sh
$ make build
mkdir -p vault/plugins
GOOS=linux GOARCH="amd64" go build -o vault/plugins/vault-plugin-auth-ssh cmd/vault-plugin-auth-ssh/main.go
```

```sh
$ vault plugin register -sha256=5bc883fc90820e344f7c0fbc73ff81953b48b7f4c0c4d4bb1fecaa1941f255c7 auth vault-plugin-auth-ssh
Success! Registered plugin: vault-plugin-auth-ssh
```
```sh
$ vault auth enable -path=ssh vault-plugin-auth-ssh
Success! Enabled vault-plugin-auth-ssh auth method at: ssh/
```
So good so far...

Using Vault version:
```sh
Vault v1.6.3 (b540be4b7ec48d0dd7512c8d8df9399d6bf84d76)
```

Trying to add the SSH CA, I get the following error:
```sh
$ vault write auth/ssh/config ssh_ca_public_keys=@sshca
Error writing data to auth/ssh/config: Error making API request.

URL: PUT https://atf.fooqueue.org:8200/v1/auth/ssh/config
Code: 500. Errors:

* 1 error occurred:
	* internal error
```

Even within the UI trying to view configuration you'll get an error:
```
Error
Ember Data Request GET /v1/auth/ssh/?help=1 returned a 500 Payload (application/json) [object Object]

1 error occurred: * Unrecognized remote plugin message: This usually means that the plugin is either invalid or simply needs to be recompiled to support the latest protocol.
```

Vault version 1.7.0 results are the same.

**Comment by 42wim** [comment]
Did you configure a correct `api_addr` ? Otherwise you get an error like that. Also look in your vault logs it should say something like:

2021-04-10T21:59:31.695+0200 [ERROR] auth.vault-plugin-auth-ssh.auth_vault-plugin-auth-ssh_87528cb3.vault-plugin-auth-ssh.vault-plugin-auth-ssh: plugin tls init: error=**"no vault api_addr found"** timestamp=2021-04-10T21:59:31.695+0200


More info about api_addr on https://www.vaultproject.io/docs/configuration#api_addr

**Comment by sh0shin** [comment]
Tried this today, and it's working!

Maybe you should give hint about the `api_addr` in the README, since this a High Availability parameter.
